services:
  frontend:
    build: ./remote-controller-app
    container_name: remotecontroller-frontend
    ports:
      - "4000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8080
    depends_on:
      - backend
    networks:
      - app-network
    restart: unless-stopped

  backend:
    build:
      context: ./remote-controller-app
      dockerfile: backend.Dockerfile
    container_name: remotecontroller-backend
    ports:
      - "8080:8000"
    volumes:
      - deep-live-cam-models:/root/.insightface/models
    environment:
      - PYTHONPATH=/app
      - ENV=production
    command: ["gunicorn", "--workers", "2", "--bind", "0.0.0.0:8000", "--timeout", "120", "api_server:app"]
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge

volumes:
  deep-live-cam-models: 