version: '3.8'

services:
  backend:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: fanxytv-backend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    volumes:
      - /dev:/dev
    privileged: true
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    container_name: fanxytv-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.dev.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend
    restart: unless-stopped 