services:
  frontend:
    build:
      context: ./remote-controller-app
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:8000
      - NEXT_PUBLIC_APP_PIN=1234
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build:
      context: ./remote-controller-app
      dockerfile: backend.Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - deep-live-cam-models:/root/.insightface/models
    command: ["gunicorn", "--workers", "1", "--bind", "0.0.0.0:8000", "--timeout", "120", "api_server:app"]
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  deep-live-cam-models: 