services:
  frontend:
    build:
      context: ./remote-controller-app
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8080
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build:
      context: ./remote-controller-app
      dockerfile: backend.Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - deep-live-cam-models:/root/.insightface/models
      - /dev:/dev
    privileged: true
    command: ["gunicorn", "--workers", "1", "--bind", "0.0.0.0:8080", "--timeout", "120", "api_server:app"]
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  deep-live-cam-models: 